name: snowflake_ml_py311
channels:
  - anaconda # For most packages
  - https://repo.anaconda.com/pkgs/snowflake # For Snowflake Specific
  - conda-forge # For DVC and Dagshub
dependencies:
  - python=3.11
  - ipykernel
  - nbconvert
  - nbformat
  - python-dotenv
  - seaborn
  - scikit-learn
  - xgboost
  - absl-py
  - anyio
  - cloudpickle
  - numpy
  - packaging
  - pandas
  - pyyaml
  - typing-extensions
  - dvc
  - pip
  - pip:
    - dagshub
    - snowflake-snowpark-python[pandas]
    - snowflake-ml-python
